---
- hosts: all
  become: yes
  tasks:
  - name: allow older password encryptions
    lineinfile:
      path: "/etc/login.defs"
      regexp: "^ENCRYPT_METHOD"
      line: "ENCRYPT_METHOD MD5"
      state: present
      create: no
      backrefs: yes
    ignore_errors: yes
  
  - name: allow login with password
    lineinfile:
      path: "/etc/ssh/sshd_config"
      regexp: "^(#)?PasswordAuthentication.*"
      line: "PasswordAuthentication yes"
      state: present
    notify:
    - restart_sshd

  - name: but not for root
    lineinfile:
      path: "/etc/ssh/sshd_config"
      regexp: "^(#)?PermitRootLogin.*"
      line: "PermitRootLogin no"
      state: present
    notify:
    - restart_sshd

  - name: update root password on the fly
    user:
      name: root
      password: "{{ otf_ssh_password }}"

  - name: update packer password on the fly
    user:
      name: packer
      password: "{{ otf_ssh_password }}"
  
  handlers:
    - name: restart_sshd
      service:
        name: sshd
        state: restarted
  
