---
- hosts: all
  become: yes
  tasks:

  - name: create a packer user
    when: 'ssh_user != "packer"'
    block:
    - name: make sure we have a wheel group
      group:
        name: wheel
        state: present
  
    - name: sudo without password for wheel group
      copy:
        content: '%wheel ALL=(ALL:ALL) NOPASSWD:ALL'
        dest: /etc/sudoers.d/wheel_nopasswd
        mode: 0440
  
    - name: add sudoers users to wheel group
      user:
        name: packer
        groups: wheel
        append: yes
        state: present
        createhome: yes

