---
- hosts: all
  become: yes
  tasks:
  - name: remove unwanted routes
    copy: 
      dest: /usr/local/bin/del-priv-default-route
      mode: 0755
      content: |
        #! /bin/bash
        
        echo "deleting default routes via private network"
        ip link | awk -F: '$1 ~ /^[0-9]/ {gsub(/ /, "", $2); print $2}' | while read intf
        do
            ip link set $intf up
        done
        sleep 1
        dhclient
        sleep 1
        ip r | grep "default via 10.[0-9]*.[0-9]*.[0-9]* dev" | while read rt
        do
            ip r del $rt
        done

  - name: configure as one-shot service
    copy:
      dest: /etc/systemd/system/del-priv-default-route
      mode: 0755
      content: |
        [Unit]
        Description=Delete unwanted default routes to private networks
        After=network-online.target
        
        [Service]
        Type=oneshot
        ExecStart=/usr/local/bin/del-priv-default-route
        RemainAfterExit=true
        StandardOutput=journal
        
        [Install]
        WantedBy=multi-user.target

  - name: enable the service
    systemd:
      name: del-priv-default-route
      enabled: yes
  
